### ISSUE TITLE
Cannot seem to find any chrome or firefox bookmarks?

### ISSUE THREAD

**Issue by lgjmac** [talengu/Wox.Plugin.BookmarkSearcher#1]
Not sure why... nothing happens in the box...

**Comment by talengu** [comment]
Hi, @lgjmac now it only support the chrome. And I test OK in the windows 10 with chrome.

**Comment by rifaterdemsahin** [comment]
i also can not see on windows 10 chrome.. is there any debug we can send ?
here : Do we need Everything service to be running
![image](https://user-images.githubusercontent.com/5270036/43676688-c6d14742-97ed-11e8-8bf7-aacad2fa0418.png)

**Comment by talengu** [comment]
@rifaterdemsahin For the BookmarkSearcher plugin, it do not need the `Everything service`. But running `Everything` is basic support for the wox other plugins, so running it is a good choice. Install it from [Everything link](https://github.com/Wox-launcher/Wox/releases/latest)

And you need to install BookmarkSearcher plugin.
Download Wox plugin packages, installing manually. If for some reason, user cannot use the `WPM` to install plugins. Users may download the plugin package to a local (ending with wox), and then drag the plugin package to Wox search box. 

Bookmarks Searcher plugin packages [download](https://github.com/talengu/Wox.Plugin.BookmarkSearcher/releases/download/v1.0/BookmarkSearcher-64FB733EFC0F11E7AB9638D547A9452B.wox)  and the plugin `Action keywords` is `b`

see more in #3

**Comment by lgjmac** [comment]
Hi.
I think there might be variation in the bookmarks folder storage for different browsers (e.g. chrome dev; firefox etc). I'll look at the python script when I have some time and send a commit request or whatever they are called!
