### ISSUE TITLE
浏览器目录不在C盘该怎么修改

### ISSUE THREAD

**Issue by M142857** [talengu/Wox.Plugin.BookmarkSearcher#10]
用的其他浏览器，centbrowser，bookmarks文件在D:\centbrowser_4.2.10.171_x64_portable\User Data\Default

看到之间问题里修改解决，
class bookmark_searcher(object):
    # in windows
    bookmark_name = os.path.join(os.path.expanduser("~"), 'AppData//Local//Google//Chrome//User Data//Default',
                                 'Bookmarks')
    # in mac
    #bookmark_name = os.path.join(os.path.expanduser("~"), 'Library/Application Support/Google/Chrome/Default',
            #                     'Bookmarks')
==========
那这种不在C盘的该怎么编辑？谢谢

**Comment by talengu** [comment]
直接给 `bookmark_name`  赋值就好了，注意用 `D://centbrowser_4.2.10.171_x64_portable//User Data//Default`  你试一试，不知道支不支持 `centbrowser`

**Comment by M142857** [comment]
哈哈哈谢谢，完全不懂python，但是查了os.path.join，又找到os.path.abspath，然后开始试，用下面的实现了。
    bookmark_name = os.path.abspath('D://centbrowser_4.2.10.171_x64_portable/User Data/Default/Bookmarks')
妙了。
弄了一下午，这种问题搜不到，准备放弃以后学点python再来，实在是放心不下注册来留言。就试出来了。

/换成//也可以

你说的赋值就是join换成abspath绝对路径嘛？还是join也可以。
感谢，看你前面的回答才觉得修改.py可行，其他wox里面bookmarks插件下都没找到相关方法。

**Comment by M142857** [comment]
哈哈哈谢谢，完全不懂python，但是查了os.path.join，又找到os.path.abspath，然后开始试，用下面的实现了。
    bookmark_name = os.path.abspath('D://centbrowser_4.2.10.171_x64_portable/User Data/Default/Bookmarks')
妙了。
弄了一下午，这种问题搜不到，准备放弃以后学点python再来，实在是放心不下注册来留言。就试出来了。

/换成//也可以

你说的赋值就是join换成abspath绝对路径嘛？还是join也可以。
感谢，看你前面的回答才觉得修改.py可行，其他wox里面bookmarks插件下都没找到相关方法。

**Comment by talengu** [comment]
好的。
