### ISSUE TITLE
Install is not working

### ISSUE THREAD

**Issue by avxkim** [talengu/Wox.Plugin.BookmarkSearcher#3]
`wpm install Bookmarks Searcher`

Nothing happens. Not appearing in plugins section. Do you still maintain this plugin?

**Comment by talengu** [comment]
Yes, I am working on it.

For your question. The `wpm` install method may not work now.

Download Wox plugin packages, installing manually. If for some reason, user cannot use the `WPM` to install plugins. Users may download the plugin package to a local (ending with wox), and then drag the plugin package to Wox search box. 

Bookmarks Searcher plugin packages [download](https://github.com/talengu/Wox.Plugin.BookmarkSearcher/releases/download/v1.0/BookmarkSearcher-64FB733EFC0F11E7AB9638D547A9452B.wox)  and the plugin `Action keywords` is `b`

**Comment by avxkim** [comment]
1. Downloaded wox file
2. Dragged that file in to search > wox reloaded > still can't see your plugin in Plugins section, also keyword is not working.

**Comment by talengu** [comment]
what is your wox version. `can't see your plugin in Plugins section` is strange. You can close the wox and reopen it . I am using wox version 1.3.424 with win10 and chrome.

**Comment by avxkim** [comment]
1.3.524 version. No, restart is not helping.

**Comment by talengu** [comment]
In v1.3.524. I have test ok. Can you find this?

![qq 20180814132327](https://user-images.githubusercontent.com/10290923/44073195-42a0109a-9fc5-11e8-907c-a061528fc30c.png)

**Comment by avxkim** [comment]
No, i don't have it, lol. I'm adding your file as you described, by dragging in a searchbar, then windows pops about installing this package, then asks for reload, reload happens, still can't see your plugin.

**Comment by talengu** [comment]
Are the other plugins which you installed OK? And python environment is ready as the wox need?
[wox install](https://github.com/Wox-launcher/Wox#installation)

**Comment by avxkim** [comment]
Other plugins are installed with WPM and working. No issues with python.

**Comment by talengu** [comment]
You can try this way to install the plugin. 

1. set the python env
![image](https://user-images.githubusercontent.com/10290923/44075680-4403f9c8-9fd0-11e8-8ce1-4b438a8a8071.png)

2. open the `Plugin Directory`
![image](https://user-images.githubusercontent.com/10290923/44074152-18d87810-9fca-11e8-9e8c-f14d18ca8cad.png)

3. unzip and put this in the  `Plugins` dir
[BookmarksSeacher-b5755b47-7896-4882-a1e1-60ba8a1e5bdd.zip](https://github.com/talengu/Wox.Plugin.BookmarkSearcher/files/2285654/BookmarksSeacher-b5755b47-7896-4882-a1e1-60ba8a1e5bdd.zip)
![image](https://user-images.githubusercontent.com/10290923/44074267-886f9730-9fca-11e8-95da-913d70c77bdc.png)

4. may need to change the `bookmark_name` in the `Plugins\BookmarksSeacher\bookmark_searcher.py` file.
chrome has a json file to record the bookmarks named `Bookmarks` .
My chrome file is in ` AppData//Local//Google//Chrome//User Data//Profile 1`. 
By default it will be in the `AppData//Local//Google//Chrome//User Data//Default`

![image](https://user-images.githubusercontent.com/10290923/44074458-38425f3a-9fcb-11e8-899d-1757050912a7.png)

5. reload and restart wox and the plugin `Action keywords` is `b`.

**Comment by avxkim** [comment]
1. Unzipped your archive
2. Put it in: C:\Users\Alexander\AppData\Local\Wox\app-1.3.524\Plugins
3. Restarted wox
4. Can't see it in plugins list

![image](https://user-images.githubusercontent.com/5739191/44075242-da549ec2-9fbd-11e8-9c2b-c97b0f2027b8.png)

**Comment by talengu** [comment]
Did you set the python env?
![image](https://user-images.githubusercontent.com/10290923/44075680-4403f9c8-9fd0-11e8-8ce1-4b438a8a8071.png)

**Comment by avxkim** [comment]
Can you try to install without choosing python directory?

**Comment by talengu** [comment]
This plugin is based on python. Without the python env setting, this plugin can not be installed.  I think there is a bookmark c# plugin can be used without python. [Wox.Plugin.BrowserBookmark](https://github.com/Wox-launcher/Wox.Plugin.BrowserBookmark) But I'm not sure it's OK. so I develop this plugin.

**Comment by talengu** [comment]
## A summary of install issue.
### Install manually
#### 1. Install wox and python
**Install wox.** You can find wox in [Wox-launcher/Wox/releases](https://github.com/Wox-launcher/Wox/releases)
**Set the python env** (I use Anaconda3) as the image.
![image](https://user-images.githubusercontent.com/10290923/44075680-4403f9c8-9fd0-11e8-8ce1-4b438a8a8071.png)

#### 2. Open the `Plugin Directory`
![image](https://user-images.githubusercontent.com/10290923/44074152-18d87810-9fca-11e8-9e8c-f14d18ca8cad.png)

#### 3. Unzip and put this in the  `Plugins` dir
[BookmarksSeacher-b5755b47-7896-4882-a1e1-60ba8a1e5bdd.zip](https://github.com/talengu/Wox.Plugin.BookmarkSearcher/files/2285654/BookmarksSeacher-b5755b47-7896-4882-a1e1-60ba8a1e5bdd.zip)

![image](https://user-images.githubusercontent.com/10290923/44074267-886f9730-9fca-11e8-95da-913d70c77bdc.png)

#### 4.  Open and Change the `bookmark_name` variable name in the `Plugins\BookmarksSeacher\bookmark_searcher.py` file.
chrome has a json file to record the bookmarks named `Bookmarks` . 
My chrome file is in ` AppData//Local//Google//Chrome//User Data//Profile 1` dir.
By default it will be in the `AppData//Local//Google//Chrome//User Data//Default`

![image](https://user-images.githubusercontent.com/10290923/44074458-38425f3a-9fcb-11e8-899d-1757050912a7.png)

#### 5. Reload and restart wox and the plugin `Action keywords` is `b`.

![image](https://raw.githubusercontent.com/talengu/Wox.Plugin.BookmarkSearcher/master/doc/demo.gif)

**Have fun!!**
