### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lunachy** [talengu/Wox.Plugin.BookmarkSearcher#9]
![微信截图_20200608164938](https://user-images.githubusercontent.com/10249962/84011081-2e068300-a9a8-11ea-9355-94223d991978.png)
split后取值应该判断下是否有内容，存在空格组成的字符串split后为空数组的情况。
![微信截图_20200608165407](https://user-images.githubusercontent.com/10249962/84011439-b38a3300-a9a8-11ea-9066-b24b485dace6.png)

**Comment by talengu** [comment]
简单有效，妙~
